config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  resources :charges, only: [:new, :create]

  resources :downgrades, only: [:create]

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  root 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :wikis, dependent: :destroy
  has_many :collaborators
  has_many :wiki_collaborations, through: :collaborators, source: :wiki

  before_create :set_role

  def set_role
    self.role ||= :standard
  end

  enum role: [:standard, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    # Creates a Stripe Customer object, for associating with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    # creates a charge based on the Customer object
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: 10_00,
      description: "Premium Membership - #{current_user.email}",
      currency: 'usd'
    )

    if charge.paid
      flash[:notice] = "Thanks for payment"
      current_user.premium!
      redirect_to root_path
    end

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to root_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership",
      amount: 10_00
    }
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create
    @user = User.find_by(email: params[:email])
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new(user: @user, wiki: @wiki)

    if @collaborator.save
      flash[:notice] = "You added a new collaborator."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error adding this collaborator."
      redirect_to @wiki
    end
  end

  def destroy
    @user = User.find_by(email: params[:email])
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.find_by(user: @user, wiki: @wiki)

    if @collaborator.destroy
      flash[:notice] = "\"#{@collaborator.id}\" was removed successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error removing that collaborator."
      redirect_to @wiki
    end
  end
end

app/controllers/downgrades_controller.rb
class DowngradesController < ApplicationController
  def create
    current_user.standard!
    current_user.wikis.update_all(:private => false )
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    ApplicationPolicy.new(current_user, @wiki).edit?

    if @wiki.save
      flash[:notice] = "Post was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Initializes a Markdown parser
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/downgrades_helper.rb
module DowngradesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/downgrades/create.html.erb
<h1>Downgrades#create</h1>
<p>Find me in app/views/downgrades/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= link_to "Home", :root %>
</div>

<div class="container">
   <% if user_signed_in? %>
     Signed in as: <strong><%= current_user.email %></strong> |
     <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
   <% else %>
     <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
     <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
   <% end %>
</div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<head>
  <h1>Blocipedia: Social, Markdown Wikis</h1>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-xs-4 col-md-4 text-center">
      </div>
      <div class="col-xs-4 col-md-4 text-center">
        <h3>Create and Share Markdown Wikis!</h3>
        <button>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %>
        </button>
        or
        <button>
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        </button>
      </div>
      <div class="col-xs-4 col-md-4 text-center">
      </div>
    </div>
  </div>
  </br>
  <div class="row">
    <div class="col-lg-6 text-center">
      <h3>Create Public Wikis!</h3>
      <button type="button" class="btn btn-default btn-lg">
        <span class="glyphicon glyphicon-asterisk"></span>
        <p>Free Plan<p>
      </button>
    </div>
    <div class="col-lg-6 text-center">
      <h3>Create Private Wikis!</h3>
      <button type="button" class="btn btn-default btn-lg">
        <span class="glyphicon glyphicon-fire"></span>
        <p>Premium Plan<p>
      </button>
    </div>
  </div>
</body>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>

  <%= f.label :body %>
  <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>

  <%= f.submit "Save", class: 'btn btn-success' %>

  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit a Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Wiki Guidelines</p>
    <ul>
      <li>Rule #1: NO REPOSTS!!!</li>
      <li>Rule #2: Always try to add something to the community.</li>
      <li>Rule #3: Nobody likes reading your excessive hashtags.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render 'form' %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>

<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to markdown(wiki.title), wiki %>
          </h4>
          <small>
            <%= markdown(wiki.body) %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>Create a New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Wiki Guidelines</p>
    <ul>
      <li>Rule #1: NO REPOSTS!!!</li>
      <li>Rule #2: Always try to add something to the community.</li>
      <li>Rule #3: Nobody likes reading your excessive hashtags.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render 'form' %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= markdown(@wiki.title) %></h1>

<div class="row">
  <div class="col-md-8">
    <h3><%= markdown(@wiki.body) %></h3>
    <hr>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
  </div>
  <hr>
  <div class="col-md-8">
    <% if @wiki.collaborators.any? %>
      <h4> Wiki Collaborators: </h4>
      <% @wiki.collaborators.each do |collabo| %>
      <h5><%= collabo.user.email %></h5>
      <%= link_to "Remove Collaborator", wiki_collaborator_path(wiki_id: @wiki.id, email: collabo.user.email), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to remove this collaborator?' } %>
      <% end %>
    <% end %>
    <hr>
  </div>
  <div class="col-md-8">
    <h4> Add a Collaborator: </h4>
    <%= form_tag(wiki_collaborators_path(wiki_id: @wiki.id)) do %>
      <%= text_field_tag :email, params[:email], placeholder: "Enter User Email" %>
      <%= submit_tag "Submit" %>
    <% end %>
    <hr>
  </div>
</div>